log:
  file:
    enable: false
    path: logs/raybot.log
    rotation_count: 2
    format: JSON
    level: ERROR
  console:
    enable: true
    format: TEXT
    level: DEBUG
hardware:
  esp:
    serial:
      port: /dev/ttyUSB0
      baud_rate: 9600
      data_bits: 8
      stop_bits: 1
      parity: NONE
      read_timeout: 1s
  pic:
    serial:
      port: /dev/ttyUSB1
      baud_rate: 9600
      data_bits: 8
      stop_bits: 1
      parity: NONE
      read_timeout: 1s
cloud:
  enable: false
  address: localhost:50051
  token: 4d24e88b41374b34a54806c0124b4052
http:
  swagger: true
  port: 3000
wifi:
  ap:
    enable: false
    ssid: Raybot AP
    password: "1111111"
    ip: 192.168.1.1
  sta:
    enable: false
    ssid: ssid
    password: password
cron:
  delete_old_command:
    schedule: "@every 1h"
    threshold: 168h   # 7 days
