LogConfig:
  type: object
  properties:
    file:
      $ref: "#/LogFileHandler"
      x-order: 1
    console:
      $ref: "#/LogConsoleHandler"
      x-order: 2
  required:
    - file
    - console

LogFileHandler:
  type: object
  properties:
    enable:
      type: boolean
      example: true
      description: Whether to enable the file log
      x-order: 1
    path:
      type: string
      example: "logs/raybot.log"
      description: The path to the file log
      x-order: 2
    rotationCount:
      type: integer
      example: 10
      description: The number of log files to keep
      x-order: 3
    level:
      type: string
      enum:
        - DEBUG
        - INFO
        - WARN
        - ERROR
      example: "DEBUG"
      description: The global log level for the application
      x-order: 4
      x-go-type: string
    format:
      type: string
      enum:
        - JSON
        - TEXT
      example: "JSON"
      description: The log format for the application
      x-order: 5
      x-go-type: string
  required:
    - enable
    - path
    - rotationCount
    - level
    - format

LogConsoleHandler:
  type: object
  properties:
    enable:
      type: boolean
      example: true
      description: Whether to enable the console log
      x-order: 1
    level:
      type: string
      enum:
        - DEBUG
        - INFO
        - WARN
        - ERROR
      example: "DEBUG"
      description: The global log level for the application
      x-order: 2
      x-go-type: string
    format:
      type: string
      enum:
        - JSON
        - TEXT
      example: "JSON"
      description: The log format for the application
      x-order: 3
      x-go-type: string
  required:
    - enable
    - level
    - format

HardwareConfig:
  type: object
  properties:
    esp:
      $ref: "#/ESPConfig"
    pic:
      $ref: "#/PICConfig"
  required:
    - esp
    - pic

PICConfig:
  type: object
  properties:
    serial:
      $ref: "#/SerialConfig"
  required:
    - serial

ESPConfig:
  type: object
  properties:
    serial:
      $ref: "#/SerialConfig"
  required:
    - serial

SerialConfig:
  type: object
  properties:
    port:
      type: string
      example: "/dev/ttyUSB0"
      description: The port name for the serial connection
      x-order: 1
    baudRate:
      type: integer
      example: 9600
      description: The baud rate for the serial connection
      x-order: 2
    dataBits:
      type: integer
      example: 8
      description: The data bits for the serial connection
      x-order: 3
    stopBits:
      type: number
      format: double
      example: 1
      description: The stop bits for the serial connection
      x-order: 4
      x-go-type: float64
    parity:
      type: string
      enum:
        - NONE
        - EVEN
        - ODD
      example: "NONE"
      description: The parity for the serial connection
      x-order: 5
      x-go-type: string
    readTimeout:
      type: number
      example: 1
      description: The read timeout for the serial connection in seconds
      x-order: 6
      minimum: 0
      x-go-type: int
  required:
    - port
    - baudRate
    - dataBits
    - stopBits
    - parity
    - readTimeout

CloudConfig:
  type: object
  properties:
    enable:
      type: boolean
      example: true
      description: Whether to enable the cloud service
      x-order: 1
    address:
      type: string
      example: "localhost:50051"
      description: The address for the cloud service
      x-order: 2
    token:
      type: string
      example: "4d24e88b41374b34a54806c0124b4052"
      description: The token for the cloud service
      x-order: 3
  required:
    - enable
    - address
    - token

HTTPConfig:
  type: object
  properties:
    port:
      type: integer
      example: 8000
      description: The port for the HTTP server
      x-order: 1
    swagger:
      type: boolean
      example: true
      description: Whether to enable the Swagger UI
      x-order: 2
  required:
    - port
    - swagger

WifiConfig:
  type: object
  properties:
    ap:
      $ref: "#/APConfig"
    sta:
      $ref: "#/STAConfig"
  required:
    - ap
    - sta

APConfig:
  type: object
  properties:
    enable:
      type: boolean
      example: true
      description: Whether to enable the AP mode
      x-order: 1
    ssid:
      type: string
      example: "raybot"
      description: The SSID for the AP mode
      x-order: 2
    password:
      type: string
      example: "password"
      description: The password for the AP mode
      x-order: 3
    ip:
      type: string
      example: "192.168.1.1"
      description: The IP address for the AP mode
      x-order: 4
  required:
    - enable
    - ssid
    - password
    - ip

STAConfig:
  type: object
  properties:
    enable:
      type: boolean
      example: true
      description: Whether to enable the STA mode
      x-order: 1
    ssid:
      type: string
      example: "raybot"
      description: The SSID for the wifi connection
      x-order: 2
    password:
      type: string
      example: "password"
      description: The password for the wifi connection
      x-order: 3
  required:
    - enable
    - ssid
    - password
